name: Secrets and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zugriff auf Secrets
        env:
          VITE_FIREBASE_API_KEY: AIzaSyCrHk-cCsZqAO5QRNVecKiO36iQGAhDOfY
          VITE_FIREBASE_AUTH_DOMAIN: portfolios-ellisarn.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: portfolios-ellisarn
          VITE_FIREBASE_STORAGE_BUCKET: portfolios-ellisarn.appspot.com
          VITE_FIREBASE_MESSAGING_SENDER_ID: 800764911155
          VITE_FIREBASE_APP_ID: 1:800764911155:web:57e3001bb44e92463c0d46
          VITE_FIREBASE_MEASUREMENT_ID: G-BBYCP7XN06
          VITE_EMAIL: ellisarn@gmail.com
          VITE_PASSWORD: SilleNra2005

        run: |
          echo $VITE_FIREBASE_API_KEY
          echo $VITE_FIREBASE_AUTH_DOMAIN
          echo $VITE_FIREBASE_PROJECT_ID
          echo $VITE_FIREBASE_STORAGE_BUCKET
          echo $VITE_FIREBASE_MESSAGING_SENDER_ID
          echo $VITE_FIREBASE_APP_ID
          echo $VITE_FIREBASE_MEASUREMENT_ID
          echo $VITE_EMAIL
          echo $VITE_PASSWORD

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
